# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
one_d = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
two_d = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
three_d = np.array([[[1, 2, 3], [4, 5, 6]]])

one_d, two_d, three_d

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[1, 2, 3],
         [4, 5, 6]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_d.shape, one_d.ndim, one_d.dtype, one_d.size, type(one_d)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
two_d.shape, two_d.ndim, two_d.dtype, two_d.size, type(two_d)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
three_d.shape, three_d.ndim, three_d.dtype, three_d.size, type(three_d)

((1, 2, 3), 3, dtype('int32'), 6, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
two_d_df = pd.DataFrame(two_d)
two_d_df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
random_array_1 = np.arange(0, 100, 3)
random_array_1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array_2 = np.random.randint(0, 10, size=(7, 2))
random_array_2

array([[5, 3],
       [6, 1],
       [0, 6],
       [5, 2],
       [3, 2],
       [7, 8],
       [0, 8]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_3 = np.random.random(size=(3, 5))
random_array_3

array([[0.84813062, 0.19528029, 0.57836721, 0.37505233, 0.26547776],
       [0.95422254, 0.48828151, 0.6874504 , 0.55620644, 0.96882348],
       [0.96033706, 0.25846446, 0.9969362 , 0.56621367, 0.68144345]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_4 = np.random.randint(0, 10, size=(4, 6))
random_array_4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

- They are the same everytime since the seed defines the randomness. The same seed will always generate the same random numbers

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_5 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
random_array_5, np.unique(random_array_5)

(array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]]),
 array([1, 2, 3, 4, 5, 7, 9]))

In [14]:
# Find the 0'th index of the latest array you created
random_array_5[0]

array([9, 1, 3, 7, 4, 9, 3])

In [15]:
# Get the first 2 rows of latest array you created
random_array_5[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_5[:2, :2]

array([[9, 1],
       [5, 3]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_6 = np.random.randint(0, 10, size=(3, 5))
zeros = np.zeros(shape=(3, 5))
random_array_6, zeros

(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [18]:
# Add the two arrays together
random_array_6 + zeros

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [19]:
# Create another array of ones of shape (5, 3)
ones = np.ones(shape=(5, 3))

In [20]:
# Try add the array of ones and the other most recent array together
random_array_6 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

- The shapes does not match each other and cannot be broadcasted together

In [21]:
# Create another array of ones of shape (3, 5)
ones = np.ones(shape=(3, 5))

In [22]:
# Subtract the new array of ones from the other most recent array
random_array_6 - ones

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [23]:
# Multiply the ones array with the latest array
random_array_6 * ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [24]:
# Take the latest array to the power of 2 using '**'
random_array_6 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [25]:
# Do the same thing with np.square()
np.square(random_array_6)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [26]:
# Find the mean of the latest array using np.mean()
np.mean(random_array_6)

3.8666666666666667

In [27]:
# Find the maximum of the latest array using np.max()
np.max(random_array_6)

9

In [28]:
# Find the minimum of the latest array using np.min()
np.min(random_array_6)

0

In [29]:
# Find the standard deviation of the latest array
np.std(random_array_6)

2.578543947441829

In [39]:
# Find the variance of the latest array
np.var(random_array_6)

6.648888888888889

In [40]:
# Reshape the latest array to (3, 5, 1)
np.reshape(random_array_6, (3, 5, 1))

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [41]:
# Transpose the latest array
random_array_6.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

- it swaps the shapes of the matrix

In [42]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_7 = np.random.randint(0, 10, size=(3, 3))
random_array_8 = np.random.randint(0, 10, size=(3, 2))

In [43]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_7, random_array_8)

array([[52, 87],
       [40, 79],
       [14, 20]])

In [44]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_9 = np.random.randint(0, 10, size=(4, 3))
random_array_10 = np.random.randint(0, 10, size=(4, 3))

In [45]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_9, random_array_10)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

- The shapes does not align, we have to transpose them

In [46]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_array_9, random_array_10.T)

array([[102,  50, 134, 120],
       [ 93,  65, 161,  90],
       [ 54,  15,  66,  57],
       [ 66,  32,  83,  81]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

- The inners must be of the same shape for the dot product to work

Let's now compare arrays.

In [47]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array_11 = np.random.randint(0, 10, size=(2, 3))
random_array_12 = np.random.randint(0, 10, size=(2, 3))

In [48]:
# Compare the two arrays with '>'
random_array_11 > random_array_12

array([[False,  True, False],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

It takes the single element of the same position in both arrays and compares them to each other

In [49]:
# Compare the two arrays with '>='
random_array_11 >= random_array_12

array([[False,  True, False],
       [False, False,  True]])

In [50]:
# Find which elements of the first array are greater than 7
random_array_11, random_array_11 > 7 # the third element is greater than 7

(array([[6, 8, 6],
        [0, 0, 8]]),
 array([[False,  True, False],
        [False, False,  True]]))

In [51]:
# Which parts of each array are equal? (try using '==')
random_array_11, random_array_12, random_array_11 == random_array_12

(array([[6, 8, 6],
        [0, 0, 8]]),
 array([[8, 3, 8],
        [2, 6, 5]]),
 array([[False, False, False],
        [False, False, False]]))

In [52]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array_11)

array([[6, 6, 8],
       [0, 0, 8]])

In [53]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array_11)

array([[0, 2, 1],
       [0, 1, 2]], dtype=int64)

In [54]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_array_11)

1

In [55]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array_11)

3

In [56]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_array_11, axis=1)

array([1, 2], dtype=int64)

In [57]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_array_11, axis=0)

array([1, 1, 0], dtype=int64)

In [58]:
# Create an array of normally distributed random numbers
np.random.normal(size=(10))

array([-2.65517605,  0.34551794, -0.39551645, -0.28913686,  0.45293633,
       -0.16606091,  0.21493883, -2.02231493, -0.94305681,  1.40395874])

In [59]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.